### ISSUE TITLE
AKS issue on namespace watch

### ISSUE THREAD

**Issue by tperelle** [logzio/logzio-k8s#16]
Hello, 

I try to deploy your example of deployment with RBAC on my AKS cluster. 
When I deploy the DaemonSet I get the following error:

```
2019-04-05 13:35:38 +0000 [info]: starting fluentd-1.3.3 pid=6 ruby="2.3.3"
2019-04-05 13:35:38 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile", "--under-supervisor"]
2019-04-05 13:35:39 +0000 [info]: gem 'fluent-plugin-concat' version '2.3.0'
2019-04-05 13:35:39 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.12'
2019-04-05 13:35:39 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.1.6'
2019-04-05 13:35:39 +0000 [info]: gem 'fluent-plugin-logzio' version '0.0.19'
2019-04-05 13:35:39 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
2019-04-05 13:35:39 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
2019-04-05 13:35:39 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.1'
2019-04-05 13:35:39 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2019-04-05 13:35:39 +0000 [info]: gem 'fluentd' version '1.3.3'
2019-04-05 13:35:39 +0000 [info]: adding match pattern="fluent.**" type="null"
2019-04-05 13:35:39 +0000 [info]: adding match pattern="logzio.**" type="detect_exceptions"
2019-04-05 13:35:39 +0000 [info]: adding filter pattern="**" type="record_modifier"
2019-04-05 13:35:39 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
Unexpected error start_namespace_watch: Exception encountered setting up namespace watch from Kubernetes API v1 endpoint https://stagingaks-77b9173a.hcp.westeurope.azmk8s.io:443/api: Failed to open TCP connection to stagingaks-77b9173a.hcp.westeurope.azmk8s.io:443 (getaddrinfo: Temporary failure in name resolution)
  /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.6/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:34:in `rescue in start_namespace_watch'
  /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.6/lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb:27:in `start_namespace_watch'
  /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-kubernetes_metadata_filter-2.1.6/lib/fluent/plugin/filter_kubernetes_metadata.rb:262:in `block in configure'
```

However I use the ServiceAccount and the ClusterRole:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluentd
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: fluentd
  namespace: kube-system
---
```

Do you know why it doesn't works ?

Thanks

**Comment by idohalevi** [comment]
@tperelle 
I will check it and get back to you

**Comment by idohalevi** [comment]
@tperelle 
Do you have more than one node?

**Comment by tperelle** [comment]
Yes I have 2 workers nodes at the moment and certainly more in the future.

**Comment by idohalevi** [comment]
@tperelle 
Not that I'm aware of. Check you manually the connection to `stagingaks-77b9173a.hcp.westeurope.azmk8s.io:443`. Again, it looks like it's a network issue and not integration one. 

One last thing, can you verify you have the same version of our docker in both nodes?

**Comment by tperelle** [comment]
Now it works, it seems to be a temporary issue to resolve the control plane DNS.

Thanks for your help
